# Generated by Django 5.0.1 on 2024-02-02 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='doctor_id',
            field=models.IntegerField(),
        ),
    ]
