# Generated by Django 5.0.1 on 2024-02-05 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='user_phone_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histories', to='home.admissions'),
        ),
    ]
