# Generated by Django 5.0.1 on 2024-02-02 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_financial_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financial',
            name='price',
            field=models.BigIntegerField(),
        ),
    ]
