# Generated by Django 5.0.1 on 2024-02-05 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_history_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='user_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
