# Generated by Django 5.0.1 on 2024-02-02 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_financial_check_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissions',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
