# Generated by Django 5.0.1 on 2024-02-04 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_admissions_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='doctor_id',
            field=models.IntegerField(),
        ),
    ]
