# Generated by Django 5.0.1 on 2024-02-06 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_history_user_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissions',
            name='time',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
