# Generated by Django 5.0.1 on 2024-02-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_history_doctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='doctor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.doctor'),
        ),
        migrations.AlterField(
            model_name='history',
            name='user_id',
            field=models.IntegerField(),
        ),
    ]
