# Generated by Django 5.0.1 on 2024-02-04 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_history_doctor_id_alter_history_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='doctor_id',
            field=models.IntegerField(),
        ),
    ]
