# Generated by Django 5.0.1 on 2024-02-06 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_rename_time_admissions_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='admissions',
            old_name='Time',
            new_name='time',
        ),
    ]
