# Generated by Django 5.0.1 on 2024-02-06 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_rename_time_admissions_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admissions',
            name='time',
        ),
    ]
